default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  username: <%= ENV.fetch("DB_USER") { 'postgres' } %>
  password: <%= ENV.fetch("DB_PASSWORD") { 'password' } %>
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { "kakeibo_development" } %>

test:
  <<: *default
  database: kakeibo_test

production:
  primary: &primary_production
    <<: *default
    database: kakeibo_production
